export const datas=[
    {name:"item1",
    price:5,
    id:1,
    img:"idalton-smith-hIrRF_sGWZg-unsplash.jpg"
    },
    {name:"item2",
    price:5,
    id:2,
    img:"yana_hurskaya-5LzS7vOoM4U-unsplash.jpg"
    },  
    {name:"item3",
    price:3,
    id:3,
    img:"wenya-luo-9IY26O8ujcM-unsplash.jpg"
    },
    {name:"item4",
    price:4,
    id:4,
    img:"isaak-alexandre-karslian-J007cgfDQBI-unsplash.jpg"
    },   
    {name:"item5",
    price:5,
    id:5,
    img:"leon-rohrwild-jUuk_7Ecetc-unsplash.jpg"
    },
    {name:"item6",
    price:4,
    id:6,
    img:"unseen-histories-nfVTrOTBICU-unsplash.jpg"
    }
]